In [1]:
import numpy as np

In [6]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))  
print(array1.shape) 

array2 = np.array([[1,2,3], [4,5,6]])
print(type(array2))  
print(array2.shape)  

array3 = np.array([[1,2,3]])
print(type(array3))  
print(array3.shape)  

<class 'list'>
<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [10]:
print(f"array1: {array1.ndim}차원, array2: {array2.ndim}차원  array3: {array3.ndim}차원")

array1: 1차원, array2: 2차원  array3: 2차원


## ndarray의 데이터 타입

In [13]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))  
print(array1, array1.dtype)  # 요소의 데이터 타입 

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [16]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)  # 요소의 데이터 타입 

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)  # 요소의 데이터 타입 

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [22]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1 = array_float.astype(np.int32)
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype(np.int32)
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

In [27]:
seq_arr = np.arange(10)
print(seq_arr)
print(seq_arr.dtype, seq_arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [31]:
zero_arr = np.zeros((3, 2), dtype='int64')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int64 (3, 2)


In [40]:
one_arr = np.ones((3, 2), dtype='int32')
print(one_arr)
print(one_arr.dtype, one_arr.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape

#### array1 = np.arange(10)
print("array1: ", array1)

# (5, 2) shape로 변환
array2 = array1.reshape(5, 2)
print("array2: ", array2)

# (2, 5) shape로 변환 
array3 = array1.reshape(2, 5)
print("array3: ", array3)

In [52]:
array1 = np.arange(10)
print("array1: ", array1)

# (5, 2) shape로 변환 -1은 가변인자
array2 = array1.reshape(-1, 2)
print("array2: ", array2)

# (2, 5) shape로 변환 -1은 가변인자 
array3 = array1.reshape(2, -1)
print("array3: ", array3)

array1:  [0 1 2 3 4 5 6 7 8 9]
array2:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3:  [[0 1 2 3 4]
 [5 6 7 8 9]]


In [59]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [72]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print("array3d: \n", array3d.tolist())

# 3차원 ndarray를 2차원으로
array2d = array3d.reshape((-1, 1))
print("array2d: \n", array2d.tolist())

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array2d: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]


## 넘파이 ndarray의 데이터 세트 선택하기 - indexing

In [78]:
array1 = np.arange(start=1, stop=10)
print("array1: ", array1)

value = array1[2]
print(f"value: {value}")
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [81]:
print(f"맨 뒤의 값: {array1[-1]}", f", 맨 뒤에서 두번째 값: {array1[-2]}")

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [85]:
array2d = array1.reshape(3, 3)
for i in range(len(array2d)):
    for j in range(len(array2d[0])):
        print(f"(row={i}, col={j}) index 가리키는 값: ", array2d[i,j])

(row=0, col=0) index 가리키는 값:  1
(row=0, col=1) index 가리키는 값:  2
(row=0, col=2) index 가리키는 값:  3
(row=1, col=0) index 가리키는 값:  4
(row=1, col=1) index 가리키는 값:  5
(row=1, col=2) index 가리키는 값:  6
(row=2, col=0) index 가리키는 값:  7
(row=2, col=1) index 가리키는 값:  8
(row=2, col=2) index 가리키는 값:  9


In [89]:
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [93]:
print("array2d[0:2, 0:2]: \n", array2d[0:2, 0:2])
print("array2d[1:3, 0:3]: \n", array2d[1:3, 0:3])

array2d[0:2, 0:2]: 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]: 
 [[4 5 6]
 [7 8 9]]


## 팬시 인덱싱

In [100]:
!pip install icecream
from icecream import ic

In [102]:
ic(array2d)
ic(array2d[[0,1], 2])
ic(array2d[[0,1], 0:2])

ic| array2d: array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
ic| array2d[[0,1], 2]: array([3, 6])
ic| array2d[[0,1], 0:2]: array([[1, 2],
                                [4, 5]])


array([[1, 2],
       [4, 5]])

## 불린 인덱싱

In [104]:
array1d = np.arange(start=1, stop=10)
print(f"array1d: {array1d}")

array1d: [1 2 3 4 5 6 7 8 9]


In [105]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [106]:
val = array1d >5
print(val, type(val), val.shape)

[False False False False False  True  True  True  True] <class 'numpy.ndarray'> (9,)


In [108]:
# 불린 인덱스로 필터링 한 결과
array1d[array1d > 5]

array([6, 7, 8, 9])

## sort

In [115]:
original_arr = np.array([3, 1, 9, 5])
print(f"original_arr : {original_arr}")

# np.sort() 로 정렬
sorted_arr = np.sort(original_arr)
print(f"sorted_arr: {sorted_arr}")
print(f"np.sort() 수행 후 원본 배열: {original_arr}")

# ndarray.sort() 로 정렬
sorted_arr2 = original_arr.sort()
print(f"sorted_arr2: {sorted_arr2}")
print(f"np.sort() 수행 후 원본 배열: {original_arr}")

original_arr : [3 1 9 5]
sorted_arr: [1 3 5 9]
np.sort() 수행 후 원본 배열: [3 1 9 5]
sorted_arr2: None
np.sort() 수행 후 원본 배열: [1 3 5 9]


In [116]:
# 내림차순 정렬
sorted_desc_arr = np.sort(original_arr)[::-1]
print("내림차순 정렬 한 배열: ", sorted_desc_arr)

내림차순 정렬 한 배열:  [9 5 3 1]


In [123]:
# axis를 적용해서 정렬
array2d = np.array([[8, 12], [7,1]])
print("array2d: \n", array2d, array2d.shape)

# 행으로 정렬
row_sorted_arr = np.sort(array2d, axis=0)
print(row_sorted_arr)

# 열로 정렬
col_sorted_arr = np.sort(array2d, axis=1)
print(col_sorted_arr)

array2d: 
 [[ 8 12]
 [ 7  1]] (2, 2)
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [128]:
# 정렬 행렬의 인덱스 반환
arr = np.array([3, 1, 9, 5])
arg_sorted_arr = np.argsort(arr)
print(arg_sorted_arr)

[1 0 3 2]


In [130]:
# 점수 오름 차순으로 이름 정렬
name_array = np.array(['의정', '우정', '국지', '재정', '승호'])
score_array = np.array([78, 84, 88, 95, 80])
index_arr = np.argsort(score_array)
name_array[index_arr]

array(['의정', '승호', '우정', '국지', '재정'], dtype='<U2')

## 내적과 전치행렬

In [132]:
# 행렬 내적
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5], [6, 7], [8, 9]])
c = np.dot(a, b)
print(c)

[[ 40  46]
 [ 94 109]]


In [134]:
d = np.array([[1,2], [3,4]])
e = np.transpose(d)
print(e)

[[1 3]
 [2 4]]
