In [1]:
import numpy as np

In [6]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))  
print(array1.shape) 

array2 = np.array([[1,2,3], [4,5,6]])
print(type(array2))  
print(array2.shape)  

array3 = np.array([[1,2,3]])
print(type(array3))  
print(array3.shape)  

<class 'list'>
<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [10]:
print(f"array1: {array1.ndim}차원, array2: {array2.ndim}차원  array3: {array3.ndim}차원")

array1: 1차원, array2: 2차원  array3: 2차원


## ndarray의 데이터 타입

In [13]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))  
print(array1, array1.dtype)  # 요소의 데이터 타입 

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [16]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)  # 요소의 데이터 타입 

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)  # 요소의 데이터 타입 

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [22]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1 = array_float.astype(np.int32)
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype(np.int32)
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32
